### ISSUE TITLE
scan_interval correctly handled?

### ISSUE THREAD

**Issue by dutch-erik** [cyberjunky/home-assistant-p2000lifeliners#2]
Hi, I noticed that new lifeliners only popup every 30 minutes while interval is being defined as:
scan_interval: 30

  - platform: p2000lifeliners
    name: P2000LLrs
    contains: Life
    scan_interval: 30

See the history below:
![afbeelding](https://user-images.githubusercontent.com/62548287/125477708-810944ff-121e-46ac-b550-a9a6a4918469.png)

**Comment by dutch-erik** [comment]
Is anyone else seeing the same?

**Comment by dutch-erik** [comment]
Hi Ron,

Can you please have a look at above? Lifeliners are only showed every 30 minutes. Looks like `scan-interval` is not working.

**Comment by cyberjunky** [comment]
Enable debug log and see how much it refreshes?
Lifeliners are not in use all the time...

**Comment by dutch-erik** [comment]
Hi Ron,

I did some investigations and compared data from http://p2000.brandweer-berkel-enschot.nl and the p2000lifeliner debug log. 
Looking at example 1 below, specifically have a look at the different times between feed time (23:26:22) and the HA-LOG debug time (23:54:02). The debug data however shows the correct time (23:26: ).

Example 1
```
http://p2000.brandweer-berkel-enschot.nl/
0923993 	23-09-21 23:26:22	A1 (DIA) Ledeboerstraat 5048AD Tilburg 131519

HA-LOG:
2021-09-23 23:54:02 DEBUG (MainThread) [custom_components.p2000lifeliners.sensor] New P2000 Lifeliners event found: Melding: A1 (DIA) Ledeboerstraat 5048AD Tilburg 131519      
Korps/Voertuig: Life Line 3      
Capcode: 0923993, at Thu, 23 Sep 2021 23:26:26 +0000

```
Example 2
```
http://p2000.brandweer-berkel-enschot.nl/
0120901 	24-09-21 00:09:12	A1 13104 13991 13114 Jan Evertsenstraat Amsterdam 91362 91363 91364

HA-LOG:
2021-09-24 00:24:02 DEBUG (MainThread) [custom_components.p2000lifeliners.sensor] New P2000 Lifeliners event found: Melding: A1 13104 13991 13114 Jan Evertsenstraat Amsterdam 91362 91363 91364      
Korps/Voertuig: Life Line 1      
Capcode: 0120901, at Fri, 24 Sep 2021 00:09:16 +0000
```
Example 3
```
http://p2000.brandweer-berkel-enschot.nl/
0120901 	24-09-21 01:35:06	A1 13104 13991 Stationsplein Amsterdam 91380 91381

HA-LOG:
2021-09-24 01:55:02 DEBUG (MainThread) [custom_components.p2000lifeliners.sensor] New P2000 Lifeliners event found: Melding: A1 13104 13991 Stationsplein Amsterdam 91380 91381      Korps/Voertuig: Life Line 1      Capcode: 0120901, at Fri, 24 Sep 2021 01:35:11 +0000
```

So if you compare all data (times) above with the data (times) below shown in Home Assistant -logbook card you see that the presentation of the Lifeliner events is shown every ~30 min only and not as soon as the event is presented in the rss-feed.

![afbeelding](https://user-images.githubusercontent.com/62548287/134662315-6e76e0cd-20bb-4f6b-ba0e-bb3948c96130.png)

I hope you see now what I mean, if not please let me know.

BTW: The scan_interval for debugging was set at 120 seconds which seems to work fine actually. So the scan_interval is working fine. Something seems to go weird with the data processing in my opinion.
Or am I wrong?

**Comment by dutch-erik** [comment]
I just realized that I mixed up the two feeds (P2000 and P2000lifeliners).
So below the feeds from: http://feeds.feedburner.com/p2000-life-liners

```
A1 (DIA) Ledeboerstraat 5048AD Tilburg 131519
Datum:Thu, 23 Sep 2021 23:26:26 +0000
Melding: A1 (DIA) Ledeboerstraat 5048AD Tilburg 131519 
Korps/Voertuig: Life Line 3 
Capcode: 0923993
```
```
A1 13104 13991 13114 Jan Evertsenstraat Amsterdam 91362 91363 91364
Datum:Fri, 24 Sep 2021 00:09:16 +0000
Melding: A1 13104 13991 13114 Jan Evertsenstraat Amsterdam 91362 91363 91364
Korps/Voertuig: Life Line 1 
Capcode: 0120901
```
```
A1 13104 13991 Stationsplein Amsterdam 91380 91381
Datum:Fri, 24 Sep 2021 01:35:11 +0000
Melding: A1 13104 13991 Stationsplein Amsterdam 91380 91381 
Korps/Voertuig: Life Line 1 
Capcode: 0120901
```
I don't think it's a differance. ;)

**Comment by cyberjunky** [comment]
You completely lost me, what exactly is the issue?
You need to enable logging to see what is going on.
The code is as good as the source are, I can do nothing about that.
You can always buy an cheap RTLSDR dongle and receiver them yourself

**Comment by dutch-erik** [comment]
Ok, fair enough, I can imagine that you lost me. ;) I'll give it another try.
My issue is the presentation in HA. When you look at the history figure below (p2000 lifeliner integration) lifeliner events are only presented every 30 minutes, so at xx:15 and xx:45 WHILE the presentation for the 'regular' P2000 integration events are presented at the moment it arrives via the RSS-Feed., so almost 'real-time'.

I enabled debug logging earlier and copied/pasted them in message above 3 days ago as 'HA-log'. I tried to compare/show there that as a new lifeliner RSS-Event arrives, let's say at xx:16, it would be presented at xx:45.

Again, there is nothing wrong with the P2000-lifeliner integration, I just try to understand why lifeliner events are not directly shown in HA while the 'regular' P2000 integration events are shown directly.

Do you have the P2000-lifeliner integration installed on your end so you can perhaps see what I mean?

![afbeelding](https://user-images.githubusercontent.com/62548287/134889097-5675fd86-61c9-4771-9fc5-9f3169c5c218.png)
